version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./html:/usr/share/nginx/html
    depends_on:
      - your_service

  personalsite:
    build:
      context: ./  # Path to your service's Dockerfile and code
      dockerfile: Dockerfile   # Name of your Dockerfile
    container_name: personalsite
    ports:
      - "8000:8000"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./html:/usr/share/nginx/html
    command: certonly --webroot --webroot-path=/usr/share/nginx/html -d your_domain.com
    depends_on:
      - nginx

networks:
  default:
    external:
      name: bridge
