version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.test.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./html:/usr/share/nginx/html
      - ./static:/static
    depends_on:
      - personalsite

  personalsite:
    build:
      context: ./  # Path to your service's Dockerfile and code
      dockerfile: Dockerfile   # Name of your Dockerfile
    container_name: personalsite
    ports:
      - "8000"

