version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./html:/usr/share/nginx/html
      - ./static:/static
    depends_on:
      - personalsite

  personalsite:
    build:
      context: ./  # Path to your service's Dockerfile and code
      dockerfile: Dockerfile   # Name of your Dockerfile
    container_name: personalsite
    environment:
      - DJANGO_ALLOWED_HOSTS=fulton.software,www.fulton.software
    ports:
      - "8000"
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./html:/usr/share/nginx/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    command: certonly --webroot --webroot-path=/var/www/html --email your-email@example.com -d fulton.software --deploy-hook "nginx -s reload"
    depends_on:
      - nginx